In [1]:
%load_ext autoreload
%autoreload 2
import json
import pandas as pd

from dfir_copilot.agent.graph import build_agent
from dfir_copilot.agent.llm import make_llm
from dfir_copilot.engine.query_engine import QueryEngine
from dfir_copilot.evidence.ledger import Ledger

engine = QueryEngine("/workspace/data/processed/three_months.parquet", timeout_s=120)
ledger = Ledger.open("IDOR-INVOICES-2020Q4", engine, analyst="Eder")
agent = build_agent(engine, ledger, make_llm(), max_steps=12)
n0 = len(ledger.entries())   # marca de inicio, para ver después qué hizo el agente
print("modelo:", agent.model_name, "| entradas del ledger:", n0)

modelo: claude-sonnet-5-5 | entradas del ledger: 110

In [4]:
r = agent.ask("¿Hay actividad anómala sobre /invoices/search? Investiga el dataset, formula hipótesis y pruébalas.")
print(r.status, "| pasos:", r.steps, "| tokens:", r.tokens)
print(r.answer or "(pausado: hay hipótesis pendientes de tu aprobación)")

AgentBusy: Hay una aprobación pendiente en este hilo: llama a resume() o resolve() primero

In [3]:
for e in ledger.entries()[n0:]:
    d = e["data"]
    if e["type"] == "tool_call":
        print(f"{e['seq']:>3} herramienta  {d['tool']:<17} {json.dumps(d['args'], ensure_ascii=False)[:110]}  {'ok' if d['ok'] else 'ERROR'}")
    elif e["type"] == "hypothesis":
        print(f"{e['seq']:>3} hipótesis    {d['hypothesis_id']}  {d['statement'][:100]}")
    elif e["type"] == "hypothesis_update":
        print(f"{e['seq']:>3} estado       {d['hypothesis_id']}  {d['from']} -> {d['to']}  ({d['decision']})")
    elif e["type"] == "agent_turn":
        print(f"{e['seq']:>3} turno        {d['status']}  pasos={d['steps']}  tokens={d['tokens']}  {d.get('error') or ''}")

112 herramienta  describe_dataset  {}  ok
133 herramienta  run_detectors     {}  ok
135 herramienta  run_query         {"sql": "SELECT user_id, status_code, count(*) n, count(distinct x_invoice_id) ids, min(timestamp_utc) t0, max  ok
137 herramienta  run_query         {"sql": "SELECT CASE WHEN user_id IN ('jacintobuyer','mantecoluser','marcianobuyer','mateuser') THEN 'grupo' E  ok
139 herramienta  run_query         {"sql": "SELECT date_trunc('month', timestamp_utc) m, CASE WHEN user_id IN ('jacintobuyer','mantecoluser','mar  ok
141 herramienta  run_query         {"sql": "SELECT user_id, src_ip, count(*) n, min(timestamp_utc) t0, max(timestamp_utc) t1, count(distinct x_in  ok
143 herramienta  run_query         {"sql": "WITH base AS (SELECT DISTINCT x_invoice_id FROM logs WHERE user_id NOT IN ('jacintobuyer','mantecolus  ok
145 herramienta  run_query         {"sql": "SELECT http_method, endpoint, x_token_type, count(*) n, count(distinct query_string) q FROM logs WHER  ok
147 herramienta  run_query         {"sql": "SELECT user_id, query_string, x_invoice_id, status_code, timestamp_utc FROM logs WHERE user_id='mateu  ok
149 herramienta  run_query         {"sql": "SELECT user_agent, count(*) n, count(distinct x_invoice_id) ids, round(avg(case when status_code>=400  ok
151 herramienta  run_query         {"sql": "SELECT user_id, count(*) n, count(distinct x_invoice_id) ids, round(avg(case when status_code>=400 th  ok
152 hipótesis    h-c48d0dda  Las cuentas websectest, developuser y websecuser (PostmanRuntime/7.25.0, 5 IPs 181.88.192.x, solo di
153 turno        needs_approval  pasos=5  tokens=54608

In [5]:
for req in agent.pending():
    print(f"{req['hypothesis_id']}: {req['estado_actual']} -> {req['estado_solicitado']}")
    print("  Hipótesis:    ", req["hipotesis"])
    print("  Justificación:", req["justificacion"])
    for ev in req["evidencia"]:
        print(f"  [{ev['tipo']}] {ev['ref']}: {ev['detalle'][:160]}")

h-60d4f260: en_prueba -> confirmada
  Hipótesis:     Cuatro cuentas (jacintobuyer, mantecoluser, marcianobuyer, mateuser) coordinadas desde 5 IPs exclusivas enumeran x_invoice_id en /invoices/search con herramientas automatizadas, con escalada en el último tercio del periodo.
  Justificación: 4 cuentas, 5 IPs exclusivas (cluster cerrado), 100% UA automatizados (Scrapy/crawler4j/wget), 7.1-7.2k invoice_id distintos vs 5001 de los pares, ~3.3k IDs fuera del conjunto común, y rampa 27-32x entre primer y último tercio. Matiz: volumen absoluto bajo (~15k/cuenta vs ~143k de pares). Pendiente d…[+26 car.]
  [hallazgo] f-725c25c75086: [high] 4 identidad(es) operan en exclusiva desde 5 IP(s): 12392 peticiones por IP frente a 25 típico por actor.
  [hallazgo] f-ae1bfb870c04: [medium] mateuser: el 100% de sus peticiones (15569 de 15569) viene de clientes automatizados: Scrapy/2.3.0 (+https://scrapy.org), crawler4j, wget.
  [hallazgo] f-829507c4430d: [medium] jacintobuyer accedió a 7200 x_invoice_id distintos, 1.44x la mediana de sus pares (5001).
  [hallazgo] f-d8125b1c75db: [high] jacintobuyer pasó de 354 peticiones en el primer tercio del periodo a 11251 en el último (31.7x); sus pares cambian 0.64x.
  [consulta] q-eff11af61f9e: SELECT user_id, status_code, count(*) n, count(distinct x_invoice_id) ids, min(timestamp_utc) t0, max(timestamp_utc) t1 FROM logs WHERE user_id IN ('jacintobuye
  [consulta] q-a57ab3175c9e: SELECT CASE WHEN user_id IN ('jacintobuyer','mantecoluser','marcianobuyer','mateuser') THEN 'grupo' ELSE 'resto' END g, user_agent, count(*) n, count(distinct u
  [consulta] q-b37a48ccc8df: WITH base AS (SELECT DISTINCT x_invoice_id FROM logs WHERE user_id NOT IN ('jacintobuyer','mantecoluser','marcianobuyer','mateuser') ) SELECT user_id, count(*)
  [consulta] q-ed81ab0ebfc7: SELECT date_trunc('month', timestamp_utc) m, CASE WHEN user_id IN ('jacintobuyer','mantecoluser','marcianobuyer','mateuser') THEN 'grupo' ELSE 'resto' END g, co

In [6]:
r = agent.resolve("approve", "Revisé la evidencia citada y coincide con mi análisis manual.")
print(r.status, "| pasos:", r.steps, "| tokens:", r.tokens)
print(r.answer)

done | pasos: 6 | tokens: 74016
## Resumen
Sí, hay actividad anómala en `/invoices/search`. Cuatro cuentas (jacintobuyer, mantecoluser, marcianobuyer, mateuser) operan como un grupo coordinado y automatizado que enumera `x_invoice_id`. El analista aprobó la hipótesis h-60d4f260 como confirmada. Aparece además un segundo grupo, más pequeño, que los detectores no marcaron.

## Hallazgos con evidencia
- **Grupo cerrado:** las 4 cuentas usan en exclusiva 5 IPs (204.210.158.207, 216.21.168.27, 24.163.83.34, 73.130.229.200, 74.88.210.56). Hacen 12.392 peticiones por IP, frente a unas 25 típicas por actor (f-725c25c75086).
- **Herramientas automatizadas:** el 100 % de su tráfico es Scrapy 2.3.0, crawler4j o wget (f-ae1bfb870c04 y los hallazgos equivalentes de las otras cuentas). Los otros 31 usuarios solo usan navegadores (q-a57ab3175c9e).
- **Enumeración:**
  - Cada cuenta toca entre 7.112 y 7.200 `invoice_id` distintos. Sus pares tocan exactamente 5.001 (f-829507c4430d y los otros tres hallazgos de amplitud).
  - Entre 3.311 y 3.363 de esos IDs por cuenta no están en el conjunto que consultan los demás usuarios (q-b37a48ccc8df).
  - Los 61.961 eventos son todos `GET /invoices/search`, con 48.315 query strings distintas (q-9bd73b7ca818).
- **Escalada:** pasan de unas 350–410 peticiones en el primer tercio a unas 11.100–11.350 en el último, es decir 27–32 veces más (f-d8125b1c75db y los otros tres hallazgos de rampa). Por mes, el grupo pasa de 1.488 peticiones en octubre a 15.120 en noviembre y 45.353 en diciembre (q-ed81ab0ebfc7). En diciembre sube a 10.179 IDs distintos, frente a 5.001 del resto.
- **Patrón de respuestas (q-eff11af61f9e, q-a6470ba84bea):**
  - Hasta el 31 de octubre solo aparecen respuestas de error (400, 406 y 408). Los primeros 200 y 201 son del 1 de noviembre.
  - Desde noviembre, wget tiene un 0 % de errores y Scrapy y crawler4j un 25 %.
  - Un HTTP 200 no prueba que se devolviera contenido.
- **Token en la URL:** la query string incluye `authtoken=ATUSER-ID-<usuario>`, es decir, una credencial en claro en el log (q-8ab3e9b38b6b). Conviene tratarla como expuesta.
- **Segundo grupo, sin marcar por los detectores:** websectest, developuser y websecuser usan PostmanRuntime/7.25.0 desde 5 IPs en 181.88.192.x. Solo actúan en diciembre y suman unas 5.074 peticiones, todas con HTTP 200 (q-159b319116a3, q-a57ab3175c9e). Cada cuenta toca unos 267–317 IDs por IP. Los nombres sugieren pruebas internas, pero es solo una suposición.
- **Contra la hipótesis:** el volumen absoluto del grupo es bajo, unas 15.500 peticiones por cuenta frente a más de 142.000 en los pares (q-4a3ccd1e6bf8). La anomalía está en su forma (rampa, amplitud, herramientas, IPs), no en el volumen. Los pares muestran un error del 33 %, más que las cuentas del grupo (q-4a3ccd1e6bf8, q-a6470ba84bea).

## Hipótesis y estado
- **h-60d4f260:** confirmada y aprobada por el analista. Los datos la respaldan, con el matiz del volumen bajo.
- **h-c48d0dda (nueva, propuesta):** el grupo Postman (websectest, developuser, websecuser) son pruebas internas autorizadas y no un segundo ataque. Está sin probar.

## Límites
- La zona horaria no está verificada (se asume UTC).
- `session_id` y `bytes_out` no tienen datos, así que no se puede medir qué contenido se devolvió ni reconstruir sesiones.
- No sé si las 5 IPs del grupo son residenciales, de VPN o de proxy. No hay enriquecimiento de IP.
- No sé si los IDs "fuera del conjunto común" existen realmente ni si pertenecen a otros clientes.
- La rampa se mide contra pares que decrecen (0,64 veces el tercio inicial), lo que amplifica el ratio.

## Próximas líneas de investigación
1. Comprobar si los ~3.300 IDs fuera del conjunto común devolvieron 200 o 201 solo para el grupo C1. Eso mide el acceso real a facturas ajenas (IDOR) y puede acotar qué se expuso. Conviene incluir los 201 y ver si hay un patrón secuencial en los IDs.
2. Investigar el origen de las 4 cuentas: ¿hubo credenciales comprometidas o cuentas creadas o alquiladas? Hay que buscar qué ocurrió el 1 de noviembre, cuando empiezan los éxitos, y revisar si el `authtoken` expuesto sirvió para pivotar. Ver también si las 5 IPs aparecen con otras identidades fuera de este dataset.
3. Validar h-c48d0dda con el inventario de pentest y desarrollo, y ver si el grupo Postman comparte IDs con C1. Si no está autorizado, tratarlo como un segundo actor.

In [7]:
display(pd.DataFrame([{"id": h["hypothesis_id"], "estado": h["status"], "hipótesis": h["statement"][:110],
                       "evidencia": len(h["evidence_refs"])} for h in agent.book.all()]))
print(ledger.verify())
print(ledger.summary()["counts"])

,id,estado,hipótesis,evidencia
0,h-60d4f260,confirmada,"Cuatro cuentas (jacintobuyer, mantecoluser, ma...",8
1,h-c48d0dda,propuesta,"Las cuentas websectest, developuser y websecus...",0

VerifyResult(ok=True, entries=155, head_hash='85ad74ec87222d6077e2eafb808eace3de9db5ee06236b063249f46df61c455b', error='')
{'case_opened': 1, 'query': 86, 'finding': 13, 'detector_run': 16, 'case_candidate': 4, 'note': 1, 'tool_call': 27, 'hypothesis': 2, 'hypothesis_update': 2, 'agent_turn': 3}

In [8]:
pend = agent._snapshot("default").values["pending"]
for p in pend:
    print(p["hypothesis_id"], "->", p["to"])
    print("\nJUSTIFICACIÓN COMPLETA:\n", p["rationale"])
    cited = set(p["evidence_refs"])

print("\nCONSULTAS CITADAS (SQL completo):")
for e in ledger.entries("query"):
    if e["data"]["query_id"] in cited:
        print(f"\n{e['data']['query_id']}  ({e['data']['rows']} filas)\n{e['data']['sql']}")

CONSULTAS CITADAS (SQL completo):

NameError: name 'cited' is not defined

In [9]:
rep = ledger.replay(engine)
print(len(rep), "consultas re-ejecutadas |", sum(r["match"] for r in rep), "coinciden con lo registrado")

print("\nPostman por cuenta:")
display(engine.query("""
    SELECT user_id, count(*) AS n, count(DISTINCT src_ip) AS ips,
           min(timestamp_utc) AS desde, max(timestamp_utc) AS hasta
    FROM logs WHERE user_agent LIKE 'PostmanRuntime%' GROUP BY 1 ORDER BY n DESC
""").df())

print("Postman por IP:")
display(engine.query("""
    SELECT src_ip, count(*) AS n, count(DISTINCT user_id) AS cuentas
    FROM logs WHERE user_agent LIKE 'PostmanRuntime%' GROUP BY 1 ORDER BY n DESC LIMIT 10
""").df())

85 consultas re-ejecutadas | 85 coinciden con lo registrado

Postman por cuenta:

       user_id     n  ips                   desde                   hasta
0  developuser  1746    5  2020-12-01 08:12:00+00  2020-12-31 18:01:00+00
1   websectest  1727    5  2020-12-01 08:09:00+00  2020-12-31 18:49:00+00
2   websecuser  1601    5  2020-12-01 08:20:00+00  2020-12-31 18:02:00+00

Postman por IP:

           src_ip     n  cuentas
0   181.88.192.16  1035        3
1   181.88.192.48  1034        3
2   181.88.192.59  1024        3
3  181.88.192.115   993        3
4   181.88.192.87   988        3

In [10]:
r = agent.resolve(
    "approve",
    "Aprobado el patrón de enumeración coordinada (cifras verificadas de forma independiente). "
    "No establece compromiso de las cuentas ni exfiltración: falta confirmar con IAM, no hay bytes_out "
    "y la zona horaria no está verificada.",
)
print(r.status, "| pasos:", r.steps, "| tokens:", r.tokens)
print(r.answer)

ValueError: No hay ninguna aprobación pendiente en este hilo

In [11]:
display(pd.DataFrame([{"id": h["hypothesis_id"], "estado": h["status"], "hipótesis": h["statement"][:120],
                       "evidencia": len(h["evidence_refs"])} for h in agent.book.all()]))
chk = ledger.verify()
print(chk)
print("HEAD HASH (anótalo en el ticket del caso):", chk.head_hash)

,id,estado,hipótesis,evidencia
0,h-60d4f260,confirmada,"Cuatro cuentas (jacintobuyer, mantecoluser, ma...",8
1,h-c48d0dda,propuesta,"Las cuentas websectest, developuser y websecus...",0

VerifyResult(ok=True, entries=155, head_hash='85ad74ec87222d6077e2eafb808eace3de9db5ee06236b063249f46df61c455b', error='')
HEAD HASH (anótalo en el ticket del caso): 85ad74ec87222d6077e2eafb808eace3de9db5ee06236b063249f46df61c455b

In [12]:
rep = ledger.replay(engine)
print(len(rep), "consultas re-ejecutadas |", sum(r["match"] for r in rep), "coinciden con lo registrado")

print("\nPostman por cuenta:")
display(engine.query("""
    SELECT user_id, count(*) AS n, count(DISTINCT src_ip) AS ips,
           min(timestamp_utc) AS desde, max(timestamp_utc) AS hasta
    FROM logs WHERE user_agent LIKE 'PostmanRuntime%' GROUP BY 1 ORDER BY n DESC
""").df())

print("Postman por IP:")
display(engine.query("""
    SELECT src_ip, count(*) AS n, count(DISTINCT user_id) AS cuentas
    FROM logs WHERE user_agent LIKE 'PostmanRuntime%' GROUP BY 1 ORDER BY n DESC LIMIT 10
""").df())

85 consultas re-ejecutadas | 85 coinciden con lo registrado

Postman por cuenta:

       user_id     n  ips                   desde                   hasta
0  developuser  1746    5  2020-12-01 08:12:00+00  2020-12-31 18:01:00+00
1   websectest  1727    5  2020-12-01 08:09:00+00  2020-12-31 18:49:00+00
2   websecuser  1601    5  2020-12-01 08:20:00+00  2020-12-31 18:02:00+00

Postman por IP:

           src_ip     n  cuentas
0   181.88.192.16  1035        3
1   181.88.192.48  1034        3
2   181.88.192.59  1024        3
3  181.88.192.115   993        3
4   181.88.192.87   988        3

In [13]:
display(engine.query("""
    SELECT extract(hour FROM timestamp_utc) AS hora_utc,
           count(*) FILTER (WHERE user_agent LIKE 'PostmanRuntime%') AS postman,
           count(*) FILTER (WHERE user_agent IN ('crawler4j','wget') OR user_agent LIKE 'Scrapy%') AS herramientas_grupo
    FROM logs GROUP BY 1 ORDER BY 1
""").df())

    hora_utc  postman  herramientas_grupo
0          0        0                2521
1          1        0                2521
2          2        0                2521
3          3        0                2521
4          4        0                2521
5          5        0                2521
6          6        0                2521
7          7        0                2862
8          8      341                2676
9          9      488                2676
10        10      488                2676
11        11      488                2676
12        12      488                2676
13        13      488                2676
14        14      488                2676
15        15      488                2676
16        16      488                2676
17        17      488                2676
18        18      341                2676
19        19        0                2676
20        20        0                2335
21        21        0                2335
22        22        0                2335
23        23        0                2335

In [14]:
print("aprobaciones pendientes:", len(agent.pending()))

aprobaciones pendientes: 0

In [15]:
from dfir_copilot.agent.hypotheses import HypothesisBook

display(pd.DataFrame([{"id": h["hypothesis_id"], "estado": h["status"], "hipótesis": h["statement"][:100]}
                      for h in HypothesisBook(ledger).all()]))

print("\nÚltimas decisiones sobre hipótesis:")
for e in ledger.entries("hypothesis_update")[-3:]:
    d = e["data"]
    print(f"  {e['seq']} {d['hypothesis_id']}: {d['from']} -> {d['to']}  ({d['decision']}, por {d['decided_by']})  {d['note'][:90]}")

print("\nÚltimos turnos del agente:")
turns = ledger.entries("agent_turn")
for t in turns[-4:]:
    d = t["data"]
    print(f"  {t['seq']} {d['status']:<15} pasos={d['steps']} tokens={d['tokens']} {(d.get('error') or '')[:70]}")

done = [t for t in turns if t["data"]["status"] == "done"]
print("\nÚLTIMA RESPUESTA DEL AGENTE:\n")
print(done[-1]["data"]["answer"] if done else "(todavía no hay ninguna respuesta final registrada)")

           id      estado                                          hipótesis
0  h-60d4f260  confirmada  Cuatro cuentas (jacintobuyer, mantecoluser, ma...
1  h-c48d0dda   propuesta  Las cuentas websectest, developuser y websecus...

Últimas decisiones sobre hipótesis:
  93 h-60d4f260: propuesta -> en_prueba  (auto, por None)
  154 h-60d4f260: en_prueba -> confirmada  (approved, por Eder)  Revisé la evidencia citada y coincide con mi análisis manual.

Últimos turnos del agente:
  110 needs_approval  pasos=5 tokens=50134
  153 needs_approval  pasos=5 tokens=54608
  155 done            pasos=6 tokens=74016

ÚLTIMA RESPUESTA DEL AGENTE:

## Resumen
Sí, hay actividad anómala en `/invoices/search`. Cuatro cuentas (jacintobuyer, mantecoluser, marcianobuyer, mateuser) operan como un grupo coordinado y automatizado que enumera `x_invoice_id`. El analista aprobó la hipótesis h-60d4f260 como confirmada. Aparece además un segundo grupo, más pequeño, que los detectores no marcaron.

## Hallazgos con evidencia
- **Grupo cerrado:** las 4 cuentas usan en exclusiva 5 IPs (204.210.158.207, 216.21.168.27, 24.163.83.34, 73.130.229.200, 74.88.210.56). Hacen 12.392 peticiones por IP, frente a unas 25 típicas por actor (f-725c25c75086).
- **Herramientas automatizadas:** el 100 % de su tráfico es Scrapy 2.3.0, crawler4j o wget (f-ae1bfb870c04 y los hallazgos equivalentes de las otras cuentas). Los otros 31 usuarios solo usan navegadores (q-a57ab3175c9e).
- **Enumeración:**
  - Cada cuenta toca entre 7.112 y 7.200 `invoice_id` distintos. Sus pares tocan exactamente 5.001 (f-829507c4430d y los otros tres hallazgos de amplitud).
  - Entre 3.311 y 3.363 de esos IDs por cuenta no están en el conjunto que consultan los demás usuarios (q-b37a48ccc8df).
  - Los 61.961 eventos son todos `GET /invoices/search`, con 48.315 query strings distintas (q-9bd73b7ca818).
- **Escalada:** pasan de unas 350–410 peticiones en el primer tercio a unas 11.100–11.350 en el último, es decir 27–32 veces más (f-d8125b1c75db y los otros tres hallazgos de rampa). Por mes, el grupo pasa de 1.488 peticiones en octubre a 15.120 en noviembre y 45.353 en diciembre (q-ed81ab0ebfc7). En diciembre sube a 10.179 IDs distintos, frente a 5.001 del resto.
- **Patrón de respuestas (q-eff11af61f9e, q-a6470ba84bea):**
  - Hasta el 31 de octubre solo aparecen respuestas de error (400, 406 y 408). Los primeros 200 y 201 son del 1 de noviembre.
  - Desde noviembre, wget tiene un 0 % de errores y Scrapy y crawler4j un 25 %.
  - Un HTTP 200 no prueba que se devolviera contenido.
- **Token en la URL:** la query string incluye `authtoken=ATUSER-ID-<usuario>`, es decir, una credencial en claro en el log (q-8ab3e9b38b6b). Conviene tratarla como expuesta.
- **Segundo grupo, sin marcar por los detectores:** websectest, developuser y websecuser usan PostmanRuntime/7.25.0 desde 5 IPs en 181.88.192.x. Solo actúan en diciembre y suman unas 5.074 peticiones, todas con HTTP 200 (q-159b319116a3, q-a57ab3175c9e). Cada cuenta toca unos 267–317 IDs por IP. Los nombres sugieren pruebas internas, pero es solo una suposición.
- **Contra la hipótesis:** el volumen absoluto del grupo es bajo, unas 15.500 peticiones por cuenta frente a más de 142.000 en los pares (q-4a3ccd1e6bf8). La anomalía está en su forma (rampa, amplitud, herramientas, IPs), no en el volumen. Los pares muestran un error del 33 %, más que las cuentas del grupo (q-4a3ccd1e6bf8, q-a6470ba84bea).

## Hipótesis y estado
- **h-60d4f260:** confirmada y aprobada por el analista. Los datos la respaldan, con el matiz del volumen bajo.
- **h-c48d0dda (nueva, propuesta):** el grupo Postman (websectest, developuser, websecuser) son pruebas internas autorizadas y no un segundo ataque. Está sin probar.

## Límites
- La zona horaria no está verificada (se asume UTC).
- `session_id` y `bytes_out` no tienen datos, así que no se puede medir qué contenido se devolvió ni reconstruir sesiones.
- No sé si las 5 IPs del grupo son residenciales, de VPN o de proxy. No hay enriquecimiento de IP.
- No sé si los IDs "fuera del conjunto común" existen realmente ni si pertenecen a otros clientes.
- La rampa se mide contra pares que decrecen (0,64 veces el tercio inicial), lo que amplifica el ratio.

## Próximas líneas de investigación
1. Comprobar si los ~3.300 IDs fuera del conjunto común devolvieron 200 o 201 solo para el grupo C1. Eso mide el acceso real a facturas ajenas (IDOR) y puede acotar qué se expuso. Conviene incluir los 201 y ver si hay un patrón secuencial en los IDs.
2. Investigar el origen de las 4 cuentas: ¿hubo credenciales comprometidas o cuentas creadas o alquiladas? Hay que buscar qué ocurrió el 1 de noviembre, cuando empiezan los éxitos, y revisar si el `authtoken` expuesto sirvió para pivotar. Ver también si las 5 IPs aparecen con otras identidades fuera de este dataset.
3. Validar h-c48d0dda con el inventario de pentest y desarrollo, y ver si el grupo Postman comparte IDs con C1. Si no está autorizado, tratarlo como un segundo actor.

In [16]:
from dfir_copilot.agent.hypotheses import HypothesisBook

print("0) Texto completo de la hipótesis h-c48d0dda:")
print(HypothesisBook(ledger).get("h-c48d0dda")["statement"])

print("\n1) Estados HTTP del grupo (el agente dice: en octubre solo 400/406/408; los primeros 200/201 son del 1 de noviembre)")
display(engine.query("""
    WITH g AS (SELECT user_id FROM logs GROUP BY 1 HAVING count(DISTINCT src_ip) <= 10)
    SELECT status_code, count(*) AS n, min(timestamp_utc) AS primera, max(timestamp_utc) AS ultima
    FROM logs WHERE user_id IN (SELECT user_id FROM g) GROUP BY 1 ORDER BY 3
""").df())

print("2) Eventos y query strings distintas del grupo (el agente dice 61.961 y 48.315)")
display(engine.query("""
    WITH g AS (SELECT user_id FROM logs GROUP BY 1 HAVING count(DISTINCT src_ip) <= 10)
    SELECT count(*) AS eventos, count(DISTINCT query_string) AS query_strings_distintas,
           count(DISTINCT x_invoice_id) AS facturas_distintas
    FROM logs WHERE user_id IN (SELECT user_id FROM g)
""").df())

print("3) User-Agents de las otras cuentas (el agente dice 'solo navegadores')")
display(engine.query("""
    WITH g AS (SELECT user_id FROM logs GROUP BY 1 HAVING count(DISTINCT src_ip) <= 10)
    SELECT user_agent, count(*) AS n, count(DISTINCT user_id) AS cuentas
    FROM logs WHERE user_id NOT IN (SELECT user_id FROM g) GROUP BY 1 ORDER BY n DESC
""").df())

0) Texto completo de la hipótesis h-c48d0dda:
Las cuentas websectest, developuser y websecuser (PostmanRuntime/7.25.0, 5 IPs 181.88.192.x, solo diciembre) son pruebas internas autorizadas de seguridad/desarrollo, no un segundo grupo de ataque.

1) Estados HTTP del grupo (el agente dice: en octubre solo 400/406/408; los primeros 200/201 son del 1 de noviembre)

   status_code      n                 primera                  ultima
0          406   4236  2020-10-01 00:00:00+00  2020-12-31 19:08:00+00
1          400   4644  2020-10-01 00:19:00+00  2020-12-31 19:39:00+00
2          408   4254  2020-10-01 00:24:00+00  2020-12-31 19:38:00+00
3          200  44868  2020-11-01 00:04:00+00  2020-12-31 23:57:00+00
4          201   3959  2020-11-01 00:07:00+00  2020-12-31 19:51:00+00

2) Eventos y query strings distintas del grupo (el agente dice 61.961 y 48.315)

   eventos  query_strings_distintas  facturas_distintas
0    61961                    48315               10181

3) User-Agents de las otras cuentas (el agente dice 'solo navegadores')

                                          user_agent       n  cuentas
0  Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537....  883858       31
1  Mozilla/5.0 (Windows NTÊx.y; Win64; x64; rv:10...  883455       31
2  Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...  883021       31
3  Mozilla/5.0 (Macintosh; Intel Mac OS XÊx.y; rv...  880728       31
4  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...  880522       31
5                              PostmanRuntime/7.25.0    5074        3

In [17]:
from dfir_copilot.evidence.ledger import query_id

r = engine.query("""
    WITH g AS (SELECT user_id FROM logs GROUP BY 1 HAVING count(DISTINCT src_ip) <= 10),
    inv AS (SELECT x_invoice_id, count(DISTINCT user_id) AS n_ident FROM logs GROUP BY 1)
    SELECT count(*) FILTER (WHERE inv.n_ident <= (SELECT count(*) FROM g)) AS peticiones_fuera,
           count(DISTINCT l.x_invoice_id) FILTER (WHERE inv.n_ident <= (SELECT count(*) FROM g)) AS facturas_fuera,
           count(*) FILTER (WHERE inv.n_ident <= (SELECT count(*) FROM g) AND l.status_code // 100 = 2) AS fuera_con_2xx
    FROM logs l JOIN inv USING (x_invoice_id) WHERE l.user_id IN (SELECT user_id FROM g)
""")
peticiones, facturas, ok2xx = r.rows[0]
print(f"peticiones={peticiones} facturas={facturas} con_2xx={ok2xx}")   # esperado: 21029, 5232, 21029

ledger.record_queries(engine.history)
qid = query_id(engine.history[-1])

ledger.note(
    f"Exposición medida por el analista: {peticiones} peticiones del grupo a {facturas} facturas fuera del conjunto "
    f"compartido, {ok2xx} con respuesta 2xx. Sin bytes_out no se puede afirmar que se devolvió contenido.",
    refs=[qid], analyst="Eder")

ledger.note(
    "Correcciones al informe del agente (turno 155): (1) los otros 31 usuarios no usan solo navegadores: las 3 cuentas "
    "TEST usan PostmanRuntime; (2) los 10.179 IDs de diciembre son la unión de 4 cuentas, no comparables con 5.001 de "
    "una cuenta; (3) su propuesta 1 ya está resuelta por la medición de exposición; (4) a verificar con el equipo de "
    "la aplicación: el authtoken tiene la forma ATUSER-ID-<usuario>, por lo que podría ser fabricable sin comprometer cuentas.",
    refs=["h-60d4f260"], analyst="Eder")

chk = ledger.verify()
print(chk.ok, "| entradas:", chk.entries)
print("HEAD HASH (anótalo en el ticket del caso):", chk.head_hash)

peticiones=21029 facturas=5232 con_2xx=21029
True | entradas: 328
HEAD HASH (anótalo en el ticket del caso): 98daec9b313cb4c6fb666221d73451d01e086ff657fe4e2214d08e311efeaa9b